### PR TITLE
DS-451: Upgrade to Node 20

### PR DESCRIPTION
**Pull request by stfurkan**
# READY FOR REVIEW

# Summary
- Upgrade to Node 20

# Review By (Date)
- End of sprint

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to the package directory in your local terminal and run `npm link`
3. Open another project that we use this package (e.g. `adapt-directory`) and remove the package `npm uninstall adapt-auth-sdk`
4. Link your local package (this branch) to the other project `npm link adapt-auth-sdk`
5. Open the `adapt-auth-sdk` folder in the other project (under node_modules) and make sure that we have `20` written in the `.nvmrc` file
6. Test the auth functions and make sure it works as expected

### CODE REVIEW

**Comment by sherakama** [comment]
@stfurkan can you tell me more about the errors you encountered and where you got stuck?

**Comment by stfurkan** [comment]
> @stfurkan can you tell me more about the errors you encountered and where you got stuck?

@sherakama I can't remember the exact errors but you can see the errors if you remove `passport-saml` and install `@node-saml/passport-saml`. It seems like there are some breaking changes between the packages.

**Comment by sherakama** [comment]
@ericbakenhus recently went through this process here: https://github.com/SU-SWS/adapt-sso-sp/pull/67/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

We don't need to change to `MultiSamlStrategy` but is there anything in that PR that helps you get past your blocker?

**Comment by stfurkan** [comment]
> @ericbakenhus recently went through this process here: https://github.com/SU-SWS/adapt-sso-sp/pull/67/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
> 
> We don't need to change to `MultiSamlStrategy` but is there anything in that PR that helps you get past your blocker?

Thanks for the suggestion @sherakama :) As far as I remember, the breaking change was related to the following (there might be some other changes too):

https://github.com/SU-SWS/adapt-auth-sdk/blob/446ce033b1975af9ea9609924d98cd36c4e10346/src/AdaptAuth.ts#L4C35-L4C58

**Comment by sherakama** [comment]
>  return res.status(401).json('UNAUTHORIZED'); 
That one is an express/next-connect issue. Assumptions were made some time ago and I've seen that before with the upgrade to next-connect 1.0.

Ok, Let's put a pin in this one. I'd like to come back to the two issues you've hit at a later time. Can you put a comment into the ticket and mark it as holding, please?

**Comment by stfurkan** [comment]
> > return res.status(401).json('UNAUTHORIZED');
> 
> That one is an express/next-connect issue. Assumptions were made some time ago and I've seen that before with the upgrade to next-connect 1.0.
> 
> Ok, Let's put a pin in this one. I'd like to come back to the two issues you've hit at a later time. Can you put a comment into the ticket and mark it as holding, please?

Done

**Pull request closed without merging**
